### PR TITLE
ci: add release workflow

### LINKED ISSUE #13: Distribute binaries using Github Releases
Hello there,

I'd like to use boon in my CI workflow. Would it be possible for you to add Releases to this repo with binaries generated for common platforms?

Thanks

### PR DESCRIPTION
**Pull request by Djiit**
Create a release workflow to build and upload assets on every tag pushed on the repository.

How to test: run the test workflow (**to be removed before merge**) (dry-run: true), and assess results.

Fixes #13

### CODE REVIEW

**Comment by Djiit** [comment]
@santhosh-tekuri I'd need your help to undesertand which bin name I can use for the action. Thx

**Comment by santhosh-tekuri** [comment]
it seems this action is using `cargo build --bin boon` to build binary.

but it should be built using `cargo build --example boon` to build binary.

I use `example` rather than `bin`, because I did not want additional dependencies required by `boon` to be added to `dependencies` section in `cargo.toml`. If I use `example` then I can add additional dependencies required by `boon` to `dev-dependencies` section

can you check some other GitHub action which allows to manually do cargo build, and upload artefact to release

**Comment by Djiit** [comment]
Release will be created only once for the total job, not 3 times (because of the matrix)

**Comment by santhosh-tekuri** [comment]
I guess long names for binary looks odd.

I created new branch `bin-release-artifact` in which I moved the example into its own `cli` crate
now you can use  https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases on this crate
use `manifest-path` in GitHub action to point to `cli` crate

I think this should make the life easier

**Comment by Djiit** [comment]
It might be easier if you open another PR from your branch then. Thank you. I'll close this one.

**Comment by santhosh-tekuri** [comment]
I have already pushed the branch. 

You can pull the branch into your repo and raise new pull request.

**Pull request closed without merging**
