### PR TITLE
Update dependencies to solve vulnerability

### PR DESCRIPTION
**Pull request by JonathanBrouwer**
The goal of this PR is to mitigate a vulnerability in a dependency of this crate
https://rustsec.org/advisories/RUSTSEC-2024-0421.html

### CODE REVIEW

**Comment by santhosh-tekuri** [comment]
- do rebase
- update rustls version in cli/Cargo.toml

**Comment by JonathanBrouwer** [comment]
I think it should be good now? @santhosh-tekuri

**Comment by santhosh-tekuri** [comment]
Cli module is not compiling. Check the logs. I guess you need to add 'ring' feature to rustls in feature module. Please compile locally and verify

**Comment by JonathanBrouwer** [comment]
Right, had to update ureq as well since it depends on an olddated rustls.
I ran cargo check on the main project but forgot that doesn't run it on the cli project :P

I'm crossing my fingers that everything is good now?

**Comment by santhosh-tekuri** [comment]
Single commit is good as we are fixing same issue with mistakes. Seems the checks are passing.

**Comment by santhosh-tekuri** [comment]
Can you update ureq version in main cargo.toml also

**Comment by JonathanBrouwer** [comment]
Done

**Comment by santhosh-tekuri** [comment]
FYI the commit message has to be modified to follow project convention:

```
scope: message

description
```

so the commit message will be

```
cargo/deps: mitigate vulnerabilities

- rustls: https://rustsec.org/advisories/RUSTSEC-2024-0336.html
- idna: https://rustsec.org/advisories/RUSTSEC-2024-0421.html
```

**Pull request merged**
